export const serviceDetailsEn = [
	{
		title: "National Emergency Number",
		provider: "National Emergency",
		number: "999",
		category: "All",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/emergency.png",
	},
	{
		title: "Police Helpline Number",
		provider: "Police",
		number: "999",
		category: "Police",
		bgCol: "bg-[#DFEFFF]",
		imgLink: "./assets/police.png",
	},
	{
		title: "Fire Service Number",
		provider: "Fire Service",
		number: "999",
		category: "Fire",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/fire-service.png",
	},
	{
		title: "Ambulance Service",
		provider: "Ambulance",
		number: "1994 - 999999",
		category: "Health",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/ambulance.png",
	},
	{
		title: "Women & Child Helpline",
		provider: "Women & Child Helpline",
		number: "109",
		category: "Help",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/emergency.png",
	},
	{
		title: "Anti-Corruption Helpline",
		provider: "Anti-Corruption",
		number: "106",
		category: "Govt.",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/emergency.png",
	},
	{
		title: "Electricity Helpline",
		provider: "Electricity Outage",
		number: "16216",
		category: "Electricity",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/emergency.png",
	},
	{
		title: "BRAC Helpline",
		provider: "BRAC",
		number: "16445",
		category: "NGO",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/emergency.png",
	},
	{
		title: "Bangladesh Railway Helpline",
		provider: "Bangladesh Railway",
		number: "163",
		category: "Travel",
		bgCol: "bg-[#FFE3E2]",
		imgLink: "./assets/emergency.png",
	},
];
